{% set version = "3.2" %}

package:
  name: idna
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/idna/idna-{{ version }}.tar.gz
  sha256: 467fbad99067910785144ce333826c71fb0e63a425657295239737f7ecd125f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - idna

about:
  home: https://github.com/kjd/idna
  license: BSD Like
  license_file: LICENSE.md
  summary: Internationalized Domain Names in Applications (IDNA).
  description: |
    A library to support the Internationalised Domain Names in Applications
    (IDNA) protocol as specified in RFC 5891. This version of the protocol
    is often referred to as "IDNA2008".

extra:
  recipe-maintainers:
    - goanpeca
    - jschueller
