schema_version: 1

context:
  name: idna
  version: "3.14"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/i/idna/idna-${{ version }}.tar.gz
  sha256: 466d810d7a2cc1022bea9b037c39728d51ae7dad40d480fc9b7d7ecf98ba8ee3

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - idna
      pip_check: true

about:
  homepage: https://github.com/kjd/idna
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Internationalized Domain Names in Applications (IDNA).
  description: |
    A library to support the Internationalised Domain Names in Applications
    (IDNA) protocol as specified in RFC 5891. This version of the protocol
    is often referred to as "IDNA2008".

extra:
  recipe-maintainers:
    - goanpeca
    - jschueller
