travis:
  secure:
    BINSTAR_TOKEN: sWcOkZiFBWGT/wOxgGzkwjleTR7merTW1ztgbKOPu9N1GqllAaG/smLy0E5YczgNn6bQn2dlwslqdv4iv+bBaLj/23z5wfIsNksjBQAEZVJdaq0DHaaVLuaRhtcH4QGhLp8VYbu0vOQjGx3lHANsM/+xd+qMa9GkZqJjD4jrdtwnQWvzUCwhgvpltJH4e491MpThXCbUS7TbECcXuYumIxFZndmJOwmSqHto9E4Ma2tViKRCbhetZ+LPDTSJeJeTWl4z6xmsnIrF/eU4PIL+QsFa6suRWhuhg+pF69seHY4Ip9Vy6+W0PZRaZh0SNJmJNQddqrK8X8zmmrVGleQN58EYQnvqk+J/29F8K2oTd1OLhhn2umT8ehOHr1+huotZMiKPd4w2wFt4RZfUBNf1Sue8vGM62vGQMQkrG1KxbZVTrNgmLE0R6P1PvNnNEnrMnQg4L3PG9h8RdeJFPrPL4X4Zq1IaJB6rhHnLJclWWbK49IIJo4WVGaQH9UuIcCRUXQ8bljli+kFjI889AA1dlC5L1wV4M1LY2gNbG+nhHZXhHFPSTd1Z++hsNKjo8KWoFjRbDYpwehQcA5MRZG9yuuuRaXU6Qbj2XVjguvReVsb0eONC0UtpnnWdPzEEVAZQbUicLdZ4wKzWYbMLxdf4RmzKGFVnSh1T6DpYym6uVFA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
